from dataclasses import dataclass


INVALID_EMPLOYEE = "INVALID_EMPLOYEE"
DUPLICATE_EMPLOYEE_ID = "DUPLICATE_EMPLOYEE_ID"
INVALID_ROOT_COUNT = "INVALID_ROOT_COUNT"
UNKNOWN_MANAGER = "UNKNOWN_MANAGER"
SELF_MANAGER = "SELF_MANAGER"
MANAGEMENT_CYCLE = "MANAGEMENT_CYCLE"
UNKNOWN_TRANSFER_EMPLOYEE = "UNKNOWN_TRANSFER_EMPLOYEE"
ROOT_MOVE_FORBIDDEN = "ROOT_MOVE_FORBIDDEN"
ALREADY_REPORTS_TO_MANAGER = "ALREADY_REPORTS_TO_MANAGER"
EMPLOYEE_NOT_FOUND = "EMPLOYEE_NOT_FOUND"
ROOT_DELETE_FORBIDDEN = "ROOT_DELETE_FORBIDDEN"
EMPLOYEE_HAS_DIRECT_REPORTS = "EMPLOYEE_HAS_DIRECT_REPORTS"


@dataclass(frozen=True)
class DomainError:
    code: str
    message: str
